model_hparams:
  d_ff: 256
  d_model: 128
  dropout: 0.1
  in_channels: 12
  n_heads: 8
  num_layers: 6
  patch_lengths:
  - 2
  - 4
  - 8
  - 8
  - 16
  - 16
  - 16
  - 16
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  seq_len: 5000
optimizer_hparams:
  lr: 2.0e-05
  lr_end: 1.0e-07
  warmup_steps: 700
