#!/usr/bin/env python
"""
Feature EDA Pipeline GPT - Consolidated ECG Feature Extraction and EDA Script

This script integrates advanced feature extraction logic from preprocessing.py 
with comprehensive exploratory data analysis (EDA) capabilities from combined_eda.py.

Enhanced Features:
- Robust channel-switching for feature extraction
- Comprehensive ECG morphological features with global statistics (from first successful lead)
- Lead group feature extraction (mean/median across clinically significant lead groups)
- Per-lead feature extraction (individual lead statistics)
- Heart Rate Variability (HRV) features
- Wavelet-based features
- Data balancing
- Parallel processing
- Comprehensive EDA plots
- Error handling and logging

Statistical Aggregations:
- First-order: mean, median, std, variance, min, max, range
- Higher-order: skewness, kurtosis, percentiles (25th, 75th), IQR

Lead-Specific Clinical Mapping:
- V1, V2: Septal & right ventricular features (P-wave, QRS focus)
- V3, V4: Anterior wall features (QRS, T-wave focus)
- V5, V6: Lateral wall features (T-wave, QT focus)
- II, III, aVF: Inferior wall features
- I, aVL: High lateral features
- II: Rhythm analysis (P-wave morphology, RR intervals)

Author: Generated by GPT-4.1 Beast Mode v3 & Edited by Andy Smithwick
Date: July 8, 2025 | Enhanced: August 5, 2025
"""

import pywt
import pandas as pd
import numpy as np
import os
import orjson
import neurokit2 as nk
from scipy import stats
import wfdb
from pathlib import Path
import argparse
from tqdm import tqdm
from joblib import Parallel, delayed
import seaborn as sns
import matplotlib.pyplot as plt
from typing import Union
from helper_code import find_records, get_sampling_frequency, load_header, load_signals, get_age, get_sex, get_label
from utils import check_interval, ecg_signal_features, st_slope

def ecg_signal_features(row: pd.Series, frequency: int, milliseconds: bool = True) -> dict:
    """
    Calculates durations and intervals from ECG wave points.
    Enhanced with better error handling and validation.
    """
    try:
        # Unpack series to variables with safe indexing
        wave_keys = ['ECG_P_Onsets', 'ECG_P_Peaks', 'ECG_P_Offsets', 'ECG_Q_Peaks', 
                    'ECG_R_Peaks', 'ECG_S_Peaks', 'ECG_T_Onsets', 'ECG_T_Peaks', 'ECG_T_Offsets']
        # Create a mapping with safe defaults
        waves = {}
        for i, key in enumerate(wave_keys):
            if i < len(row) and not pd.isna(row.iloc[i]):
                waves[key] = row.iloc[i]
            elif key in row.index and not pd.isna(row[key]):
                waves[key] = row[key]
            else:
                waves[key] = np.nan
        # Compute durations and intervals with validation
        features = {}
        # P wave duration
        if not (pd.isna(waves['ECG_P_Offsets']) or pd.isna(waves['ECG_P_Onsets'])):
            features['P_wave_duration'] = waves['ECG_P_Offsets'] - waves['ECG_P_Onsets']
        else:
            features['P_wave_duration'] = np.nan
        # PR interval
        if not (pd.isna(waves['ECG_Q_Peaks']) or pd.isna(waves['ECG_P_Onsets'])):
            features['PR_interval'] = waves['ECG_Q_Peaks'] - waves['ECG_P_Onsets']
        else:
            features['PR_interval'] = np.nan
        # PR segment
        if not (pd.isna(waves['ECG_Q_Peaks']) or pd.isna(waves['ECG_P_Offsets'])):
            features['PR_segment'] = waves['ECG_Q_Peaks'] - waves['ECG_P_Offsets']
        else:
            features['PR_segment'] = np.nan
        # QRS duration
        if not (pd.isna(waves['ECG_S_Peaks']) or pd.isna(waves['ECG_Q_Peaks'])):
            features['QRS_duration'] = waves['ECG_S_Peaks'] - waves['ECG_Q_Peaks']
        else:
            features['QRS_duration'] = np.nan
        # QT interval
        if not (pd.isna(waves['ECG_T_Offsets']) or pd.isna(waves['ECG_Q_Peaks'])):
            features['QT_interval'] = waves['ECG_T_Offsets'] - waves['ECG_Q_Peaks']
        else:
            features['QT_interval'] = np.nan
        # ST segment
        if not (pd.isna(waves['ECG_T_Onsets']) or pd.isna(waves['ECG_S_Peaks'])):
            features['ST_segment'] = waves['ECG_T_Onsets'] - waves['ECG_S_Peaks']
        else:
            features['ST_segment'] = np.nan
        # Convert to time units
        scale = 1000 / frequency if milliseconds else 1 / frequency
        for key in features:
            if not pd.isna(features[key]):
                features[key] = features[key] * scale
        return features
    except Exception as e:
        print(f"Error in ecg_signal_features: {e}")
        return {}

# --- Helper Functions from combined_eda.py ---
def get_json(path):
    with open(path, 'r') as f:
        return orjson.loads(f.read())

def load_ecg_data(exam_id, search_directory):
    mat_filename = f"{exam_id}.mat"
    hea_filename = f"{exam_id}.hea"
    for dirpath, _, filenames in os.walk(search_directory):
        if mat_filename in filenames and hea_filename in filenames:
            mat_filepath = os.path.join(dirpath, mat_filename)
            hea_filepath = os.path.join(dirpath, hea_filename)
            try:
                header = load_header(mat_filepath[:-4])
                data, _ = load_signals(mat_filepath[:-4])
                return data, header
            except Exception as e:
                print(f"Error loading {mat_filepath}: {e}")
                return None, None
    return None, None

def extract_basic_features(record_path):
    try:
        header = load_header(record_path + '.hea')
        age = get_age(header)
        is_male = 1 if get_sex(header) == 'Male' else 0
        chagas = get_label(header)
        return {'age': age, 'is_male': is_male, 'chagas': chagas}
    except Exception:
        return None

def extract_advanced_ecg_features(signal, sampling_rate, failure_counters):
    features = {}
    rr_interval_lengths = []
    try:
        lead_signal = signal[:, 0]
        signals, info = nk.ecg_process(lead_signal, sampling_rate=sampling_rate)
        peaks = info["ECG_R_Peaks"]
        rr_interval_lengths.append(len(peaks))
        if len(peaks) >= 4:
            morph_features = [
                'ECG_P_Duration', 'ECG_P_Amplitude', 'ECG_QRS_Duration', 
                'ECG_QRS_Amplitude', 'ECG_T_Duration', 'ECG_T_Amplitude', 
                'ECG_QT_Interval', 'ECG_QTc_Interval'
            ]
            for feature in morph_features:
                if feature in signals:
                    feature_values = signals[feature].dropna()
                    if not feature_values.empty:
                        features[f'{feature}_mean'] = feature_values.mean()
                        features[f'{feature}_std'] = feature_values.std()
            rate_values = signals['ECG_Rate'].dropna()
            if not rate_values.empty:
                features['Heart_Rate_Mean'] = rate_values.mean()
            else:
                features['Heart_Rate_Mean'] = np.nan
            features['signal_skewness'] = stats.skew(lead_signal)
            features['signal_kurtosis'] = stats.kurtosis(lead_signal)
            tkeo_signal = nk.ecg_tkeo(lead_signal)
            features['tkeo_mean'] = np.mean(tkeo_signal)
            features['tkeo_std'] = np.std(tkeo_signal)
            if len(peaks) > 20 and np.std(np.diff(peaks)) > 0:
                try:
                    hrv_time = nk.hrv_time(peaks, sampling_rate=sampling_rate, show=False)
                    features.update(hrv_time.iloc[0].to_dict())
                    hrv_poincare = nk.hrv_poincare(peaks, sampling_rate=sampling_rate, show=False)
                    features.update(hrv_poincare.iloc[0].to_dict())
                    hrv_fragmentation = nk.hrv_fragmentation(peaks, sampling_rate=sampling_rate, show=False)
                    features.update(hrv_fragmentation.iloc[0].to_dict())
                except Exception:
                    failure_counters['hrv_failures'] += 1
                    pass
    except Exception:
        failure_counters['single_lead_processing_failures'] += 1
        pass
    if signal.ndim > 1 and signal.shape[1] > 1:
        try:
            lead1_signal = signal[:, 0]
            lead2_signal = signal[:, 1]
            signals_I, _ = nk.ecg_process(lead1_signal, sampling_rate=sampling_rate)
            signals_II, _ = nk.ecg_process(lead2_signal, sampling_rate=sampling_rate)
            features['qrs_axis'] = nk.ecg_axis(signals_I, signals_II)
            features['t_axis'] = nk.ecg_axis(signals_I, signals_II, wave='T')
            features['p_axis'] = nk.ecg_axis(signals_I, signals_II, wave='P')
            if features.get('qrs_axis') is not None and features.get('t_axis') is not None:
                features['qrs_t_angle'] = abs(features['qrs_axis'] - features['t_axis'])
        except Exception:
            failure_counters['axis_failures'] += 1
            pass
    return features, rr_interval_lengths

def extract_wavelet_features(record_path):
    try:
        signals, _ = wfdb.rdsamp(record_path)
        ecg_signal = signals[:, 0]
        coeffs = pywt.wavedec(ecg_signal, 'db4', level=4)
        cA4, cD4, cD3, cD2, cD1 = coeffs
        features = {
            'wavelet_energy_d1': np.sum(np.square(cD1)),
            'wavelet_energy_d2': np.sum(np.square(cD2)),
            'wavelet_energy_d3': np.sum(np.square(cD3)),
            'wavelet_energy_d4': np.sum(np.square(cD4)),
            'wavelet_energy_a4': np.sum(np.square(cA4)),
            'wavelet_std_d1': np.std(cD1),
            'wavelet_std_d2': np.std(cD2),
            'wavelet_std_d3': np.std(cD3),
            'wavelet_std_d4': np.std(cD4),
            'wavelet_std_a4': np.std(cA4),
        }
        return features
    except Exception:
        return None

# --- Lead-Specific Feature Mapping ---
LEAD_FEATURE_MAPPING = {
    # Standard 12-lead ECG mapping (0-indexed)
    'I': 0, 'II': 1, 'III': 2, 'aVR': 3, 'aVL': 4, 'aVF': 5,
    'V1': 6, 'V2': 7, 'V3': 8, 'V4': 9, 'V5': 10, 'V6': 11
}

# Clinical feature significance by lead groups
LEAD_GROUPS = {
    'septal_rv': ['V1', 'V2'],          # Septal & right ventricular
    'anterior': ['V3', 'V4'],           # Anterior wall
    'lateral': ['V5', 'V6'],            # Lateral wall
    'inferior': ['II', 'III', 'aVF'],   # Inferior wall
    'high_lateral': ['I', 'aVL'],       # High lateral
    'rhythm_analysis': ['II'],          # Best for rhythm/P-wave analysis
}

# Comprehensive statistical aggregations based on research
AGGREGATION_METHODS = ['mean', 'median', 'std', 'var', 'min', 'max', 'skew', 'kurt', 'q25', 'q75', 'range', 'iqr']

def calculate_comprehensive_stats(data):
    """Calculate comprehensive statistical features for ECG data."""
    if len(data) == 0 or np.all(np.isnan(data)):
        return {stat: np.nan for stat in AGGREGATION_METHODS}
    
    data_clean = data[~np.isnan(data)]
    if len(data_clean) == 0:
        return {stat: np.nan for stat in AGGREGATION_METHODS}
    
    stats_dict = {}
    stats_dict['mean'] = np.mean(data_clean)
    stats_dict['median'] = np.median(data_clean)
    stats_dict['std'] = np.std(data_clean)
    stats_dict['var'] = np.var(data_clean)
    stats_dict['min'] = np.min(data_clean)
    stats_dict['max'] = np.max(data_clean)
    stats_dict['skew'] = stats.skew(data_clean)
    stats_dict['kurt'] = stats.kurtosis(data_clean)
    stats_dict['q25'] = np.percentile(data_clean, 25)
    stats_dict['q75'] = np.percentile(data_clean, 75)
    stats_dict['range'] = stats_dict['max'] - stats_dict['min']
    stats_dict['iqr'] = stats_dict['q75'] - stats_dict['q25']
    
    return stats_dict

def extract_lead_specific_features(signals, frequency, record_path): #TODO: Kelvin see this
    """Extract features from specific ECG leads based on clinical significance."""
    lead_features = {}
    # Store per-lead stats for lead group features
    group_feature_values = {
        'septal_rv': {'P_wave_duration': [], 'P_wave_amplitude': [], 'QRS_duration': []},
        'anterior': {'QRS_duration': [], 'QRS_amplitude': [], 'T_wave_duration': [], 'T_wave_amplitude': []},
        'lateral': {'T_wave_duration': [], 'T_wave_amplitude': [], 'QT_interval': [], 'QTc_interval': []},
        'inferior': {'QRS_duration': [], 'QRS_amplitude': [], 'QT_interval': []},
        'high_lateral': {'QRS_duration': [], 'QRS_amplitude': []},
        'rhythm_analysis': {'P_wave_duration': [], 'P_wave_amplitude': [], 'RR_interval': []},
    }
    # Map feature names to NeuroKit column names
    feature_map = {
        'P_wave_duration': 'ECG_P_Duration',
        'P_wave_amplitude': 'ECG_P_Amplitude',
        'QRS_duration': 'ECG_QRS_Duration',
        'QRS_amplitude': 'ECG_QRS_Amplitude',
        'T_wave_duration': 'ECG_T_Duration',
        'T_wave_amplitude': 'ECG_T_Amplitude',
        'QT_interval': 'ECG_QT_Interval',
        'QTc_interval': 'ECG_QTc_Interval',
        'RR_interval': None,  # Will be handled separately
    }
    # Extract features for each individual lead group #TODO Kelvin see this
    for group_name, lead_names in LEAD_GROUPS.items():
        for lead_name in lead_names:
            if lead_name in LEAD_FEATURE_MAPPING:
                lead_idx = LEAD_FEATURE_MAPPING[lead_name]
                if lead_idx < signals.shape[1]:
                    try:
                        lead_signal = signals[:, lead_idx]
                        # Basic signal statistics
                        signal_stats = calculate_comprehensive_stats(lead_signal)
                        for stat_name, stat_value in signal_stats.items():
                            lead_features[f'{lead_name}_{stat_name}'] = stat_value
                        # Neurokit2 processing for specific features
                        try:
                            ecg_signals, info = nk.ecg_process(lead_signal, sampling_rate=frequency)
                            # Extract key morphological features based on lead specialization
                            if lead_name in ['V1', 'V2']:
                                features_of_interest = ['ECG_P_Duration', 'ECG_P_Amplitude', 'ECG_QRS_Duration']
                            elif lead_name in ['V3', 'V4']:
                                features_of_interest = ['ECG_QRS_Duration', 'ECG_QRS_Amplitude', 'ECG_T_Duration', 'ECG_T_Amplitude']
                            elif lead_name in ['V5', 'V6']:
                                features_of_interest = ['ECG_T_Duration', 'ECG_T_Amplitude', 'ECG_QT_Interval', 'ECG_QTc_Interval']
                            elif lead_name in ['II', 'III', 'aVF']:
                                features_of_interest = ['ECG_QRS_Duration', 'ECG_QRS_Amplitude', 'ECG_QT_Interval']
                            elif lead_name == 'II':
                                features_of_interest = ['ECG_P_Duration', 'ECG_P_Amplitude', 'ECG_Rate']
                            else:
                                features_of_interest = ['ECG_QRS_Duration', 'ECG_QRS_Amplitude']
                            for feature in features_of_interest:
                                if feature in ecg_signals.columns:
                                    feature_values = ecg_signals[feature].dropna()
                                    if not feature_values.empty:
                                        feature_stats = calculate_comprehensive_stats(feature_values.values)
                                        for stat_name, stat_value in feature_stats.items():
                                            lead_features[f'{lead_name}_{feature}_{stat_name}'] = stat_value
                                        # For group aggregation, map back to group_feature_values
                                        for group_feat, nk_feat in feature_map.items():
                                            if nk_feat == feature and group_feat in group_feature_values[group_name]:
                                                # Use mean for this lead
                                                group_feature_values[group_name][group_feat].append(feature_values.mean())
                            # R-peaks for HRV (only for rhythm lead)
                            if lead_name == 'II' and 'ECG_R_Peaks' in info:
                                peaks = info['ECG_R_Peaks']
                                if len(peaks) > 3:
                                    rr_intervals = np.diff(peaks) / frequency * 1000  # ms
                                    if len(rr_intervals) > 0:
                                        # For group aggregation
                                        group_feature_values['rhythm_analysis']['RR_interval'].append(np.mean(rr_intervals))
                                        rr_stats = calculate_comprehensive_stats(rr_intervals)
                                        for stat_name, stat_value in rr_stats.items():
                                            lead_features[f'{lead_name}_RR_{stat_name}'] = stat_value
                        except Exception as e:
                            if lead_idx < 5:
                                print(f"Warning: NeuroKit processing failed for {lead_name}: {e}")
                            continue
                    except Exception as e:
                        print(f"Error processing lead {lead_name}: {e}")
                        continue
    # Now compute lead group features (mean and median) for each group-feature
    for group_name, feats in group_feature_values.items():
        for feat, values in feats.items():
            if len(values) > 0:
                lead_features[f'{group_name}_{feat}_mean'] = np.mean(values)
                lead_features[f'{group_name}_{feat}_median'] = np.median(values)
            else:
                lead_features[f'{group_name}_{feat}_mean'] = np.nan
                lead_features[f'{group_name}_{feat}_median'] = np.nan
    return lead_features

# --- Step 2: Unified Feature Extraction Function ---

def extract_all_features(record_relative_path: str, train_data_folder: Path) -> Union[pd.DataFrame, str]:
    """
    Extracts a comprehensive set of features from an ECG record,
    including both global and lead-specific features.
    """
    record_path = str(train_data_folder / record_relative_path)
    if not os.path.exists(record_path + '.hea'):
        print(f"Missing .hea file: {record_path + '.hea'}")
        return record_relative_path
    if not os.path.exists(record_path + '.mat'):
        print(f"Missing .mat file: {record_path + '.mat'}")
        return record_relative_path

    header = load_header(record_path)
    signals, _ = load_signals(record_path)
    frequency = get_sampling_frequency(header)

    all_features = {}
    successful_channels = []
    failure_count = 0
    
    # Try to extract global features (use first successful channel)
    for channel in range(min(12, signals.shape[1])):
        try:
            ecg_signals, info = nk.ecg_process(signals[:, channel], sampling_rate=frequency)
            correct_waves = check_interval(info)

            if correct_waves.shape[0] == 0:
                continue

            # Morphological and ST slope features (global)
            morph_features = correct_waves.apply(lambda x: ecg_signal_features(x, frequency), axis=1, result_type='expand')
            morph_features['ST_slope'] = correct_waves.apply(lambda x: st_slope(ecg_signals, int(x['ECG_S_Peaks']), int(x['ECG_T_Onsets'])), axis=1)
            
            # HRV features (global)
            try:
                hrv_features = nk.hrv_time(ecg_signals, sampling_rate=frequency)
            except Exception:
                hrv_features = pd.DataFrame()
            
            # Wavelet features (global, from first lead)
            wavelet_features = extract_wavelet_features(record_path)
            wavelet_df = pd.DataFrame([wavelet_features]) if wavelet_features else pd.DataFrame()

            # Enhanced global statistics
            agg_morph_features = pd.DataFrame()
            for col in morph_features.columns:
                if morph_features[col].notna().any():
                    col_stats = calculate_comprehensive_stats(morph_features[col].dropna().values)
                    for stat_name, stat_value in col_stats.items():
                        agg_morph_features[f'{col}_{stat_name}'] = [stat_value]

            # Combine global features
            aggregated_features = pd.concat([agg_morph_features, hrv_features, wavelet_df], axis=1)
            successful_channels.append(channel)
            break  # Use first successful channel for global features

        except Exception as e:
            if failure_count < 3:
                print(f"Global feature extraction failed for {record_relative_path} channel {channel}: {e}")
            failure_count += 1
    
    # Extract lead-specific features
    try:
        lead_specific_features = extract_lead_specific_features(signals, frequency, record_path)
        all_features.update(lead_specific_features)
    except Exception as e:
        print(f"Lead-specific feature extraction failed for {record_relative_path}: {e}")

    # Combine all features
    if len(successful_channels) > 0:
        # Convert global features to dict and merge
        if not aggregated_features.empty:
            agg_dict = aggregated_features.iloc[0].to_dict()
            all_features.update(agg_dict)
        
        # Create final DataFrame
        combined_features = pd.DataFrame([all_features])
        base_record_id = Path(record_relative_path).name
        combined_features['exam_id'] = base_record_id  # Store as string, not int
        combined_features['relative_path'] = record_relative_path
        return combined_features
    
    return record_relative_path  # Return relative_path if all channels fail

# --- Step 3: Main Execution Workflow ---

def main():
    """Main function to run the feature extraction and EDA pipeline."""
    parser = argparse.ArgumentParser(description='Feature Extraction and EDA Pipeline')
    parser.add_argument('--train', type=str, required=True, help='Path to the training data folder (WFDB format, .hea and .mat files)')
    parser.add_argument('--output', type=str, required=True, help='Path to the output folder')
    parser.add_argument('--seed', type=int, default=42, help='Seed for reproducibility')
    parser.add_argument('--jobs', type=int, default=-1, help='Number of jobs for parallel processing')
    args = parser.parse_args()

    train_data_folder = Path(args.train)
    from datetime import datetime
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_folder = Path(args.output) / f'run_{timestamp}'
    output_folder.mkdir(parents=True, exist_ok=True)

    # --- Metadata Extraction from .hea files ---
    print("Extracting metadata from .hea files...")
    record_stems = find_records(str(train_data_folder))
    metadata = []
    for record_id in tqdm(record_stems):
        meta = extract_basic_features(str(train_data_folder / record_id))
        if meta is None:
            print(f"Skipping {record_id} at {train_data_folder}: missing or invalid metadata (age, sex, or chagas label)")
            continue
        base_record_id = Path(record_id).name
        meta['exam_id'] = base_record_id  # Store as string, not int
        meta['relative_path'] = record_id  # <--- Add this line
        metadata.append(meta)
    metadata_df = pd.DataFrame(metadata)
    print(f"Loaded metadata for {len(metadata_df)} records.")
    print("Unique values in 'chagas' column:", metadata_df['chagas'].unique())

    # --- Data Balancing (now using metadata from .hea files) ---
    # The metadata is now sourced directly from .hea files (age, sex, chagas label)
    # Robustly identify negatives and positives regardless of type
    def is_negative(val):
        return val in [False, 0, 'False', '0', 'false', 'FALSE']
    def is_positive(val):
        return val in [True, 1, 'True', '1', 'true', 'TRUE']
    negatives = metadata_df[metadata_df['chagas'].apply(is_negative)]
    positives = metadata_df[metadata_df['chagas'].apply(is_positive)]
    n_positive = positives.shape[0]

    if negatives.shape[0] == 0 and positives.shape[0] == 0:
        print("No records with valid chagas labels found. Exiting.")
        return
    elif negatives.shape[0] == 0:
        print("No negative (chagas == False/0) samples found. Processing all positives only.")
        balanced_df = positives.copy()
    elif positives.shape[0] == 0:
        print("No positive (chagas == True/1) samples found. Processing all negatives only.")
        balanced_df = negatives.copy()
    elif negatives.shape[0] < n_positive:
        print(f"Not enough negatives to balance. Using all {negatives.shape[0]} negatives and {n_positive} positives.")
        balanced_df = pd.concat([negatives, positives])
    else:
        balanced_df = pd.concat([
            negatives.sample(n=n_positive, random_state=args.seed),
            positives
        ])
    records_to_process = balanced_df['relative_path'].values.tolist()  # Use relative_path for processing
    print(f"Dataset contains {balanced_df.shape[0]} records: {positives.shape[0]} positives and {negatives.shape[0]} negatives.")
    print("Sample of records to process:", records_to_process[:5])
    
    # --- Parallel Feature Extraction ---
    print("Starting feature extraction...")
    results = Parallel(n_jobs=args.jobs)(
        delayed(extract_all_features)(record_id, train_data_folder) for record_id in tqdm(records_to_process)
    )

    successful_features = [res for res in results if isinstance(res, pd.DataFrame)]
    error_records = [res for res in results if isinstance(res, str)]
    print(f"\nSuccessfully processed {len(successful_features)} records.")
    print(f"Failed to process {len(error_records)} records on all channels.")

    # --- Finalize DataFrame ---
    if not successful_features:
        print("No features were extracted. Exiting.")
        return

    df_features = pd.concat(successful_features, ignore_index=True)
    # Ensure exam_id is string in both DataFrames for merge
    df_features['exam_id'] = df_features['exam_id'].astype(str)
    balanced_df['exam_id'] = balanced_df['exam_id'].astype(str)
    df_final = df_features.merge(balanced_df, on='exam_id', how='inner')
    df_final.drop(columns=['HRV_SDANN1', 'HRV_SDNNI1', 'HRV_SDANN2', 'HRV_SDNNI2', 'HRV_SDANN5', 'HRV_SDNNI5'], inplace=True, errors='ignore')
    df_final.fillna(df_final.median(numeric_only=True), inplace=True)

    # --- NaN Tracking ---
    nan_counts = df_features.isna().sum(axis=1)
    nan_report = pd.DataFrame({
        'exam_id': df_features['exam_id'],
        'relative_path': df_features['relative_path'],
        'num_nans': nan_counts
    })
    nan_report.to_csv(output_folder / 'final_nan_counts.csv', index=False)
    print("Saved NaN counts per record to final_nan_counts.csv")

    # --- EDA Plotting ---
    print("Generating EDA plots...")
    # 1. Age Distribution
    plt.figure(figsize=(12, 5))
    sns.histplot(data=df_final, x='age', hue='is_male', multiple='stack', bins=30)
    plt.title('Age Distribution by Gender')
    plt.xlabel('Age'); plt.ylabel('Count')
    plt.legend(title='Gender', labels=['Female', 'Male'])
    plt.savefig(output_folder / 'age_distribution.png')
    plt.close()

    # 2. Correlation Heatmap (sample of key features to avoid overcrowding)
    plt.figure(figsize=(20, 15))
    # Select a subset of meaningful features for correlation
    key_correlation_features = [col for col in df_final.columns if any(x in col for x in [
        'P_wave_duration_mean', 'QRS_duration_mean', 'QT_interval_mean', 'ST_slope_mean',
        'wavelet_energy', 'V1_', 'V2_', 'II_', 'age', 'HRV_'
    ]) and col not in ['exam_id', 'relative_path', 'chagas', 'is_male']][:50]  # Limit to 50 features
    
    if key_correlation_features:
        corr = df_final[key_correlation_features + ['age', 'chagas']].corr(numeric_only=True)
        sns.heatmap(corr, annot=False, cmap='viridis', fmt='.2f')
        plt.title('Key Feature Correlation Heatmap')
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)
        plt.tight_layout()
    plt.savefig(output_folder / 'correlation_heatmap.png')
    plt.close()

    # 3. Lead-specific feature comparison
    plt.figure(figsize=(20, 15))
    lead_features = [col for col in df_final.columns if any(lead in col for lead in ['V1_', 'V2_', 'V3_', 'V4_', 'V5_', 'V6_', 'II_']) and 'mean' in col][:12]
    
    if lead_features:
        for i, feature in enumerate(lead_features):
            plt.subplot(3, 4, i + 1)
            sns.boxplot(x='chagas', y=feature, data=df_final)
            plt.title(f'{feature} by Chagas Status')
            plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(output_folder / 'lead_specific_features.png')
        plt.close()

    # 4. Traditional key features boxplots
    key_features_for_plot = []
    # Look for features that exist in the dataframe
    potential_features = ['age', 'P_wave_duration_mean', 'QRS_duration_mean', 'QT_interval_mean', 'ST_slope_mean', 'wavelet_energy_a4']
    for feature in potential_features:
        if feature in df_final.columns:
            key_features_for_plot.append(feature)
    
    if key_features_for_plot:
        plt.figure(figsize=(20, 10))
        for i, feature in enumerate(key_features_for_plot):
            plt.subplot(2, 3, i + 1)
            sns.boxplot(x='chagas', y=feature, data=df_final)
            plt.title(f'{feature} by Chagas Status')
        plt.tight_layout()
        plt.savefig(output_folder / 'feature_boxplots.png')
        plt.close()

    # 5. Statistical summary of enhanced features
    feature_summary = df_final.describe()
    feature_summary.to_csv(output_folder / 'feature_summary_statistics.csv')
    print("Saved comprehensive feature statistics to feature_summary_statistics.csv")

    # --- Save Final Outputs ---
    print("Saving final datasets...")
    df_final.to_csv(output_folder / 'final_features_balanced.csv', index=False)
    if error_records:
        pd.DataFrame(error_records, columns=['exam_id']).to_csv(output_folder / 'final_error_records.csv', index=False)

    print(f"\nPipeline complete. Outputs are saved in '{output_folder}'.")

if __name__ == '__main__':
    main()
