#!/usr/bin/env python
"""
Feature EDA Pipeline GPT - Consolidated ECG Feature Extraction and EDA Script

This script integrates advanced feature extraction logic from preprocessing.py 
with comprehensive exploratory data analysis (EDA) capabilities from combined_eda.py.

Features:
- Robust channel-switching for feature extraction
- Comprehensive ECG morphological features
- Heart Rate Variability (HRV) features
- Wavelet-based features
- Data balancing
- Parallel processing
- Comprehensive EDA plots
- Error handling and logging

Author: Generated by GPT-4.1 Beast Mode v3 & Edited by Andy Smithwick
Date: July 8, 2025
"""

import pywt
import pandas as pd
import numpy as np
import os
import orjson
import neurokit2 as nk
from scipy import stats
import wfdb
from pathlib import Path
import argparse
from tqdm import tqdm
from joblib import Parallel, delayed
import seaborn as sns
import matplotlib.pyplot as plt
from typing import Union
from helper_code import find_records, get_sampling_frequency, load_header, load_signals, get_age, get_sex, get_label
from utils import check_interval, ecg_signal_features, st_slope

def ecg_signal_features(row: pd.Series, frequency: int, milliseconds: bool = True) -> dict:
    """
    Calculates durations and intervals from ECG wave points.
    Enhanced with better error handling and validation.
    """
    try:
        # Unpack series to variables with safe indexing
        wave_keys = ['ECG_P_Onsets', 'ECG_P_Peaks', 'ECG_P_Offsets', 'ECG_Q_Peaks', 
                    'ECG_R_Peaks', 'ECG_S_Peaks', 'ECG_T_Onsets', 'ECG_T_Peaks', 'ECG_T_Offsets']
        # Create a mapping with safe defaults
        waves = {}
        for i, key in enumerate(wave_keys):
            if i < len(row) and not pd.isna(row.iloc[i]):
                waves[key] = row.iloc[i]
            elif key in row.index and not pd.isna(row[key]):
                waves[key] = row[key]
            else:
                waves[key] = np.nan
        # Compute durations and intervals with validation
        features = {}
        # P wave duration
        if not (pd.isna(waves['ECG_P_Offsets']) or pd.isna(waves['ECG_P_Onsets'])):
            features['P_wave_duration'] = waves['ECG_P_Offsets'] - waves['ECG_P_Onsets']
        else:
            features['P_wave_duration'] = np.nan
        # PR interval
        if not (pd.isna(waves['ECG_Q_Peaks']) or pd.isna(waves['ECG_P_Onsets'])):
            features['PR_interval'] = waves['ECG_Q_Peaks'] - waves['ECG_P_Onsets']
        else:
            features['PR_interval'] = np.nan
        # PR segment
        if not (pd.isna(waves['ECG_Q_Peaks']) or pd.isna(waves['ECG_P_Offsets'])):
            features['PR_segment'] = waves['ECG_Q_Peaks'] - waves['ECG_P_Offsets']
        else:
            features['PR_segment'] = np.nan
        # QRS duration
        if not (pd.isna(waves['ECG_S_Peaks']) or pd.isna(waves['ECG_Q_Peaks'])):
            features['QRS_duration'] = waves['ECG_S_Peaks'] - waves['ECG_Q_Peaks']
        else:
            features['QRS_duration'] = np.nan
        # QT interval
        if not (pd.isna(waves['ECG_T_Offsets']) or pd.isna(waves['ECG_Q_Peaks'])):
            features['QT_interval'] = waves['ECG_T_Offsets'] - waves['ECG_Q_Peaks']
        else:
            features['QT_interval'] = np.nan
        # ST segment
        if not (pd.isna(waves['ECG_T_Onsets']) or pd.isna(waves['ECG_S_Peaks'])):
            features['ST_segment'] = waves['ECG_T_Onsets'] - waves['ECG_S_Peaks']
        else:
            features['ST_segment'] = np.nan
        # Convert to time units
        scale = 1000 / frequency if milliseconds else 1 / frequency
        for key in features:
            if not pd.isna(features[key]):
                features[key] = features[key] * scale
        return features
    except Exception as e:
        print(f"Error in ecg_signal_features: {e}")
        return {}

# --- Helper Functions from combined_eda.py ---
def get_json(path):
    with open(path, 'r') as f:
        return orjson.loads(f.read())

def load_ecg_data(exam_id, search_directory):
    mat_filename = f"{exam_id}.mat"
    hea_filename = f"{exam_id}.hea"
    for dirpath, _, filenames in os.walk(search_directory):
        if mat_filename in filenames and hea_filename in filenames:
            mat_filepath = os.path.join(dirpath, mat_filename)
            hea_filepath = os.path.join(dirpath, hea_filename)
            try:
                header = load_header(mat_filepath[:-4])
                data, _ = load_signals(mat_filepath[:-4])
                return data, header
            except Exception as e:
                print(f"Error loading {mat_filepath}: {e}")
                return None, None
    return None, None

def extract_basic_features(record_path):
    try:
        header = load_header(record_path + '.hea')
        age = get_age(header)
        is_male = 1 if get_sex(header) == 'Male' else 0
        chagas = get_label(header)
        return {'age': age, 'is_male': is_male, 'chagas': chagas}
    except Exception:
        return None

def extract_advanced_ecg_features(signal, sampling_rate, failure_counters):
    features = {}
    rr_interval_lengths = []
    try:
        lead_signal = signal[:, 0]
        signals, info = nk.ecg_process(lead_signal, sampling_rate=sampling_rate)
        peaks = info["ECG_R_Peaks"]
        rr_interval_lengths.append(len(peaks))
        if len(peaks) >= 4:
            morph_features = [
                'ECG_P_Duration', 'ECG_P_Amplitude', 'ECG_QRS_Duration', 
                'ECG_QRS_Amplitude', 'ECG_T_Duration', 'ECG_T_Amplitude', 
                'ECG_QT_Interval', 'ECG_QTc_Interval'
            ]
            for feature in morph_features:
                if feature in signals:
                    feature_values = signals[feature].dropna()
                    if not feature_values.empty:
                        features[f'{feature}_mean'] = feature_values.mean()
                        features[f'{feature}_std'] = feature_values.std()
            rate_values = signals['ECG_Rate'].dropna()
            if not rate_values.empty:
                features['Heart_Rate_Mean'] = rate_values.mean()
            else:
                features['Heart_Rate_Mean'] = np.nan
            features['signal_skewness'] = stats.skew(lead_signal)
            features['signal_kurtosis'] = stats.kurtosis(lead_signal)
            tkeo_signal = nk.ecg_tkeo(lead_signal)
            features['tkeo_mean'] = np.mean(tkeo_signal)
            features['tkeo_std'] = np.std(tkeo_signal)
            if len(peaks) > 20 and np.std(np.diff(peaks)) > 0:
                try:
                    hrv_time = nk.hrv_time(peaks, sampling_rate=sampling_rate, show=False)
                    features.update(hrv_time.iloc[0].to_dict())
                    hrv_poincare = nk.hrv_poincare(peaks, sampling_rate=sampling_rate, show=False)
                    features.update(hrv_poincare.iloc[0].to_dict())
                    hrv_fragmentation = nk.hrv_fragmentation(peaks, sampling_rate=sampling_rate, show=False)
                    features.update(hrv_fragmentation.iloc[0].to_dict())
                except Exception:
                    failure_counters['hrv_failures'] += 1
                    pass
    except Exception:
        failure_counters['single_lead_processing_failures'] += 1
        pass
    if signal.ndim > 1 and signal.shape[1] > 1:
        try:
            lead1_signal = signal[:, 0]
            lead2_signal = signal[:, 1]
            signals_I, _ = nk.ecg_process(lead1_signal, sampling_rate=sampling_rate)
            signals_II, _ = nk.ecg_process(lead2_signal, sampling_rate=sampling_rate)
            features['qrs_axis'] = nk.ecg_axis(signals_I, signals_II)
            features['t_axis'] = nk.ecg_axis(signals_I, signals_II, wave='T')
            features['p_axis'] = nk.ecg_axis(signals_I, signals_II, wave='P')
            if features.get('qrs_axis') is not None and features.get('t_axis') is not None:
                features['qrs_t_angle'] = abs(features['qrs_axis'] - features['t_axis'])
        except Exception:
            failure_counters['axis_failures'] += 1
            pass
    return features, rr_interval_lengths

def extract_wavelet_features(record_path):
    try:
        signals, _ = wfdb.rdsamp(record_path)
        ecg_signal = signals[:, 0]
        coeffs = pywt.wavedec(ecg_signal, 'db4', level=4)
        cA4, cD4, cD3, cD2, cD1 = coeffs
        features = {
            'wavelet_energy_d1': np.sum(np.square(cD1)),
            'wavelet_energy_d2': np.sum(np.square(cD2)),
            'wavelet_energy_d3': np.sum(np.square(cD3)),
            'wavelet_energy_d4': np.sum(np.square(cD4)),
            'wavelet_energy_a4': np.sum(np.square(cA4)),
            'wavelet_std_d1': np.std(cD1),
            'wavelet_std_d2': np.std(cD2),
            'wavelet_std_d3': np.std(cD3),
            'wavelet_std_d4': np.std(cD4),
            'wavelet_std_a4': np.std(cA4),
        }
        return features
    except Exception:
        return None

# --- Step 2: Unified Feature Extraction Function ---

def extract_all_features(record_relative_path: str, train_data_folder: Path) -> Union[pd.DataFrame, str]:
    """
    Extracts a comprehensive set of features from an ECG record,
    iterating through channels for robustness.
    """
    record_path = str(train_data_folder / record_relative_path)
    if not os.path.exists(record_path + '.hea'):
        print(f"Missing .hea file: {record_path + '.hea'}")
        return record_relative_path
    if not os.path.exists(record_path + '.mat'):
        print(f"Missing .mat file: {record_path + '.mat'}")
        return record_relative_path

    header = load_header(record_path)
    signals, _ = load_signals(record_path)
    frequency = get_sampling_frequency(header)

    failure_count = 0
    for channel in range(12):
        try:
            ecg_signals, info = nk.ecg_process(signals[:, channel], sampling_rate=frequency)
            correct_waves = check_interval(info)

            if correct_waves.shape[0] == 0:
                continue

            # Morphological and ST slope features
            morph_features = correct_waves.apply(lambda x: ecg_signal_features(x, frequency), axis=1, result_type='expand')
            morph_features['ST_slope'] = correct_waves.apply(lambda x: st_slope(ecg_signals, int(x['ECG_S_Peaks']), int(x['ECG_T_Onsets'])), axis=1)
            
            # HRV features
            try:
                hrv_features = nk.hrv_time(ecg_signals, sampling_rate=frequency)
            except Exception:
                hrv_features = pd.DataFrame()
            
            # Wavelet features
            wavelet_features = extract_wavelet_features(record_path)
            wavelet_df = pd.DataFrame([wavelet_features]) if wavelet_features else pd.DataFrame()

            # Aggregate morphological features
            agg_morph_features = morph_features.aggregate(['mean', 'std', 'min', 'max']).unstack().to_frame().T
            agg_morph_features.columns = ['_'.join(col).strip() for col in agg_morph_features.columns.values]

            # Combine all features for the record
            combined_features = pd.concat([agg_morph_features, hrv_features, wavelet_df], axis=1)
            base_record_id = Path(record_relative_path).name
            # Output only exam_id (base name) as the main identifier
            combined_features['exam_id'] = base_record_id  # Store as string, not int
            combined_features['relative_path'] = record_relative_path
            return combined_features

        except Exception as e:
            if failure_count < 5:
                print(f"Feature extraction failed for {record_relative_path} channel {channel}: {e}")
            failure_count += 1
    return record_relative_path  # Return relative_path if all channels fail

# --- Step 3: Main Execution Workflow ---

def main():
    """Main function to run the feature extraction and EDA pipeline."""
    parser = argparse.ArgumentParser(description='Feature Extraction and EDA Pipeline')
    parser.add_argument('--train', type=str, required=True, help='Path to the training data folder (WFDB format, .hea and .mat files)')
    parser.add_argument('--output', type=str, required=True, help='Path to the output folder')
    parser.add_argument('--seed', type=int, default=42, help='Seed for reproducibility')
    parser.add_argument('--jobs', type=int, default=-1, help='Number of jobs for parallel processing')
    args = parser.parse_args()

    train_data_folder = Path(args.train)
    from datetime import datetime
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_folder = Path(args.output) / f'run_{timestamp}'
    output_folder.mkdir(parents=True, exist_ok=True)

    # --- Metadata Extraction from .hea files ---
    print("Extracting metadata from .hea files...")
    record_stems = find_records(str(train_data_folder))
    metadata = []
    for record_id in tqdm(record_stems):
        meta = extract_basic_features(str(train_data_folder / record_id))
        if meta is None:
            print(f"Skipping {record_id} at {train_data_folder}: missing or invalid metadata (age, sex, or chagas label)")
            continue
        base_record_id = Path(record_id).name
        meta['exam_id'] = base_record_id  # Store as string, not int
        meta['relative_path'] = record_id  # <--- Add this line
        metadata.append(meta)
    metadata_df = pd.DataFrame(metadata)
    print(f"Loaded metadata for {len(metadata_df)} records.")
    print("Unique values in 'chagas' column:", metadata_df['chagas'].unique())

    # --- Data Balancing (now using metadata from .hea files) ---
    # The metadata is now sourced directly from .hea files (age, sex, chagas label)
    # Robustly identify negatives and positives regardless of type
    def is_negative(val):
        return val in [False, 0, 'False', '0', 'false', 'FALSE']
    def is_positive(val):
        return val in [True, 1, 'True', '1', 'true', 'TRUE']
    negatives = metadata_df[metadata_df['chagas'].apply(is_negative)]
    positives = metadata_df[metadata_df['chagas'].apply(is_positive)]
    n_positive = positives.shape[0]

    if negatives.shape[0] == 0 and positives.shape[0] == 0:
        print("No records with valid chagas labels found. Exiting.")
        return
    elif negatives.shape[0] == 0:
        print("No negative (chagas == False/0) samples found. Processing all positives only.")
        balanced_df = positives.copy()
    elif positives.shape[0] == 0:
        print("No positive (chagas == True/1) samples found. Processing all negatives only.")
        balanced_df = negatives.copy()
    elif negatives.shape[0] < n_positive:
        print(f"Not enough negatives to balance. Using all {negatives.shape[0]} negatives and {n_positive} positives.")
        balanced_df = pd.concat([negatives, positives])
    else:
        balanced_df = pd.concat([
            negatives.sample(n=n_positive, random_state=args.seed),
            positives
        ])
    records_to_process = balanced_df['relative_path'].values.tolist()  # Use relative_path for processing
    print(f"Dataset contains {balanced_df.shape[0]} records: {positives.shape[0]} positives and {negatives.shape[0]} negatives.")
    print("Sample of records to process:", records_to_process[:5])
    
    # --- Parallel Feature Extraction ---
    print("Starting feature extraction...")
    results = Parallel(n_jobs=args.jobs)(
        delayed(extract_all_features)(record_id, train_data_folder) for record_id in tqdm(records_to_process)
    )

    successful_features = [res for res in results if isinstance(res, pd.DataFrame)]
    error_records = [res for res in results if isinstance(res, str)]
    print(f"\nSuccessfully processed {len(successful_features)} records.")
    print(f"Failed to process {len(error_records)} records on all channels.")

    # --- Finalize DataFrame ---
    if not successful_features:
        print("No features were extracted. Exiting.")
        return

    df_features = pd.concat(successful_features, ignore_index=True)
    # Ensure exam_id is string in both DataFrames for merge
    df_features['exam_id'] = df_features['exam_id'].astype(str)
    balanced_df['exam_id'] = balanced_df['exam_id'].astype(str)
    df_final = df_features.merge(balanced_df, on='exam_id', how='inner')
    df_final.drop(columns=['HRV_SDANN1', 'HRV_SDNNI1', 'HRV_SDANN2', 'HRV_SDNNI2', 'HRV_SDANN5', 'HRV_SDNNI5'], inplace=True, errors='ignore')
    df_final.fillna(df_final.median(numeric_only=True), inplace=True)

    # --- NaN Tracking ---
    nan_counts = df_features.isna().sum(axis=1)
    nan_report = pd.DataFrame({
        'exam_id': df_features['exam_id'],
        'relative_path': df_features['relative_path'],
        'num_nans': nan_counts
    })
    nan_report.to_csv(output_folder / 'final_nan_counts.csv', index=False)
    print("Saved NaN counts per record to final_nan_counts.csv")

    # --- EDA Plotting ---
    print("Generating EDA plots...")
    # 1. Age Distribution
    plt.figure(figsize=(12, 5))
    sns.histplot(data=df_final, x='age', hue='is_male', multiple='stack', bins=30)
    plt.title('Age Distribution by Gender')
    plt.xlabel('Age'); plt.ylabel('Count')
    plt.legend(title='Gender', labels=['Female', 'Male'])
    plt.savefig(output_folder / 'age_distribution.png')
    plt.close()

    # 2. Correlation Heatmap
    plt.figure(figsize=(20, 15))
    corr = df_final.corr(numeric_only=True)
    sns.heatmap(corr, annot=False, cmap='viridis')
    plt.title('Feature Correlation Heatmap')
    plt.savefig(output_folder / 'correlation_heatmap.png')
    plt.close()

    # 3. Boxplots for key features
    key_features_for_plot = ['age', 'P_wave_duration_mean', 'QRS_duration_mean', 'QT_interval_mean', 'ST_slope_mean', 'wavelet_energy_a4']
    plt.figure(figsize=(20, 10))
    for i, feature in enumerate(key_features_for_plot):
        if feature in df_final.columns:
            plt.subplot(2, 3, i + 1)
            sns.boxplot(x='chagas', y=feature, data=df_final)
            plt.title(f'{feature} by Chagas Status')
    plt.tight_layout()
    plt.savefig(output_folder / 'feature_boxplots.png')
    plt.close()

    # --- Save Final Outputs ---
    print("Saving final datasets...")
    df_final.to_csv(output_folder / 'final_features_balanced.csv', index=False)
    if error_records:
        pd.DataFrame(error_records, columns=['exam_id']).to_csv(output_folder / 'final_error_records.csv', index=False)

    print(f"\nPipeline complete. Outputs are saved in '{output_folder}'.")

if __name__ == '__main__':
    main()
