model_hparams:
  activation: gelu
  augmentations: flip,shuffle,jitter
  batch_size: 4
  checkpoint_monitor_metric: val_challenge_score
  d_ff: 2048
  d_model: 256
  data_path: ../training_data/
  dropout: 0.1
  e_layers: 8
  enc_in: 12
  epochs: 10
  n_heads: 8
  no_inter_attn: false
  num_class: 1
  num_leads: 12
  num_records: 365369
  output_attention: false
  patch_len_list: 2,4,8
  pos_weight: 10.92780825
  pred_len: 1
  seq_len: 2000
  single_channel: false
  split_file: ../train_val_test_sets.csv
  task_name: classification
  use_single_window: true
  windowing_method: entire_recording
optimizer_hparams:
  lr: 2.0e-05
  lr_end: 1.0e-07
  warmup_steps: 700
